baseURL: http://example.org/
languageCode: ja-jp
title: blog.aklaswad.com
theme: hugo-theme-tokiwa
canonifyurls: true
UglyURLs: true
permalinks:
  blog: /:year/:filename
params:
  env: production
  description: 帰ってきた。
  useChineseFonts: false

  footer: |
    &copy; aklaswad [Github](https://github.com/aklaswad) | [Twitter](https://twitter.com/aklaswad)
  social:
    twitter: https://twitter.com/aklaswad
    github: https://github.com/aklaswad

