baseURL: https://blog.aklaswad.com/
languageCode: ja-jp
title: blog.aklaswad.com
theme: PaperMod
canonifyurls: true
UglyURLs: true
permalinks:
  blog: /:year/:filename
menu:
  main:
  - identifier: archives
    name: archives
    url: /archives/
    weight: -110
paginate: 30

params:
  defaultTheme: light
  disableThemeToggle: true
  homeInfoParams:
    Content: 帰ってきた
  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/aklaswad"
    - name: "github"
      url: "https://github.com/aklaswad"
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

